# Generated by Django 2.2.3 on 2020-06-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=100),
        ),
    ]
