# Generated by Django 2.2.3 on 2020-06-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_auto_20200604_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='genre',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_id',
            field=models.CharField(max_length=500),
        ),
    ]
