# Generated by Django 2.2.3 on 2020-06-04 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20200604_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
