# Generated by Django 3.0.6 on 2020-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_remove_ratings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='movie_id',
            field=models.CharField(max_length=20),
        ),
    ]
