# Generated by Django 3.0.6 on 2020-06-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='neo4j_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_movie', models.CharField(max_length=50)),
                ('movie_name', models.CharField(max_length=10)),
                ('similarity', models.DecimalField(decimal_places=0, default=0.0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='svd_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('movie_id', models.CharField(max_length=10)),
                ('rating', models.DecimalField(decimal_places=0, default=0.0, max_digits=8)),
            ],
        ),
    ]
